default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: capstone_development
  username: postgres
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: capstone_test
  username: postgres
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: capstone_production
  username: postgres
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
  