default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost

development:
  <<: *default
  database: db/Final_Capstone_Back_End_development

test:
  <<: *default
  database: db/Final_Capstone_Back_End_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
